### ISSUE TITLE
NFT Filter Page Bugs - Release 6.1.0

### ISSUE THREAD

**Issue by TheMad-J-Hatter** [pellartech/curate#532] opened 2022-03-24 14:51 UTC
**Describe the bug**
A few key bugs that are not working on the new NFT Filter page. 

1. When selecting the filter button for a second time (while in the same search session), the filter does not remember my previous choices. For example, if I select 'ON' for Verified Curator's, then 'Apply', then return back to the filter, I have to input all criteria again.
2. When filtering by Verified Curator's, the search gives me results from the current verified owner and not the author. This should change to Verified Authors of the NFTs only.
3. When selecting 'Has Offers', there are only 4 results, is this correct?  
4. When I select 'Newly Minted' (my search bar is blank), the first result I have isn't new and was sold back in November 2021. Can 'Newly Minted' option be limited to the last week or last 30 days please?  
5. Under Price, when selecting a different token (USDC and SOS), nothing changes; the price remains in XCUR. Please can this be amended to suit. 
6. Price 'From' and 'To' doesn't seem to work. Any range I choose (e.g. 5 - 20 or 1 to 100 XCUR), just presents all results no matter the price and does not filter them correctly. 

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - OS: Android
 - Version: 12

**Comment by madtocc** [comment] 2022-03-24 15:14
I was going to push haha, glad you sent this before.
let's go step by step
1- I can't reproduce on iOS or Android video reference:

https://user-images.githubusercontent.com/12486417/159948867-9cd1fe93-8dff-4149-8bed-0b61add023bb.mov



2- Ok, this will be fixed when even is back online

3- When selecting 'Has Offers', there are only 4 results, is this correct? what else have you selected? If you selected just has offers and buy now & auction it should show you all active ones that has offers. If you just select has offers and un-select buy now. it will only show the offers for auction. if you unselect buy now & auction it will only show the ones that are not listed and have offers.



5 - this is not intended to change the UI. From my perspective it only allows you to search for a known price like I want to filter things below 100 USD. I don't know how much is a XCUR or SOS for instance. The price on the UI will show both XCUR and USD. 

4, 6 - I need to debug and see I will update soon

**Comment by TheMad-J-Hatter** [comment] 2022-03-24 15:50
Hey @madtocc, thanks for your response. I'm glad you didn't submit. Tbh, for all new releases, we should test them prior to release, just in case. Please can you tag me in all new releases and I will do a once over on the new features/enhancements etc. 

1. I'm afraid I can't see the video you uploaded. Do you understand point number one or should I create a video for you and Even? 

2. Noted

3. Noted, I only had Has Offer selected. I wanted to see how many were not for sale via Auction or Buy Now, but had an offer. I guess we only have 4 results for this so far. 

4. & 6  - Noted, will await your debugging results.

5. In which case, can we please remove SOS and just have USDC for now. In the future, I would like us to be able to show our $USD prices throughout the app in different currencies. Something a user can change in their settings that applies to the entire platform.

**Closed as completed** 2022-06-30 02:06 UTC
Labels: ready to review, Tweak, URGENT
