### ISSUE TITLE
Error showing after changing user Profile Description

### ISSUE THREAD

**Issue by Catherineanne91** [pellartech/curate#326] opened 2021-11-06 08:31 UTC
User tries to change Profile Description without changing the username

Expected Outcome: Updated Profile Description
Actual Outcome: Error showing "Sorry, Username is taken"

shertrades@gmail.com
![photo_2021-11-03_17-09-04](https://user-images.githubusercontent.com/93180831/140603389-6badfd9f-5f80-42ed-9223-4b13526bea63.jpg)

**Comment by madtocc** [comment] 2021-11-10 19:53
This is currently a problem that we face with web. We are working in re-routing the app + UI upgrade for v4.1 
This is the same issue as https://github.com/pellartech/curate/issues/249#issuecomment-961401632 can take a look at this comment for more details. Any type of share in app (product and profile) currently does not work for web.

**Comment by madtocc** [comment] 2021-11-26 13:29
Did you receive any other reports regarding this? Maybe it is fixed now. I'm not able to reproduce. @Catherineanne91, if you change your profile description do you receive this error message?

**Comment by Catherineanne91** [comment] 2021-11-27 12:09
Hi. I believe this is fixed. Was able to successfully update my profile now. Thank you!

**Comment by madtocc** [comment] 2021-11-29 13:06
Thank you for the feedback :)

**Closed by madtocc** 2021-11-29 13:06 UTC
Labels: investigate
